#!/bin/bash

if [ $# -ne 3 ]; then
  echo "Usage:"
  echo "    check_disk_used <fqdn> <directory> <threshold>"
  exit
fi

if [ ! -d $2 ]; then
  echo "No such folder ($2) CRITICAL"
  exit 2
fi

let "crit = $3 * 1024"
let "warn = $3 * 1024 * 80 / 100"

diskused=`du -s $2 | awk '{print $1}'`
if [ $diskused -lt $warn ]; then
  echo "$1 remotebackup usage is OK: $diskused of $crit at $2"
  exit
elif [ $diskused -lt $crit ]; then
  echo "$1 remotebackup usage is WARN: $diskused of $crit at $2"
  exit 1
else
  echo "$1 remotebackup usage is CRITICAL: $diskused of $crit at $2"
  exit 2
fi
exit 3
