#!/bin/bash

if [ $# -ne 3 ]; then
  echo "Usage:"
  echo "    check_newewst_file_age <directory> <warn secs> <crit secs>"
  exit
fi

file="$1/`ls -t $1 | head -1`"

if [ ! -f $file ]; then
  echo "EMPTY FOLDER ($file) CRITICAL"
  exit 2
fi

output=`/usr/lib/nagios/plugins/check_file_age -w $2 -c $3 -W 400 -C 0 $file`
retval=$?
if [ $retval -ne 0 ]; then
  echo $output
  exit $retval
fi
echo "NEWEST_FILE_AGE OK"
