if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
export LANG=en_US.UTF-8
export PS1='[\u@\[\e[36;1m\]\h\[\e[0m\] \W]\$ '
export HISTSIZE=9999

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups

# default editor vim
export EDITOR=/usr/bin/vim

alias vi='vim'
alias grep='grep --color'
GREP_COLOR=31

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    alias ll='ls -lh --color=tty'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'
fi

# puppet restart
if [ -f /var/log/syslog ]; then
  alias pr="/etc/init.d/puppet restart; tail -f /var/log/syslog | grep puppetd"
else
  alias pr="/etc/init.d/puppet restart; tail -f /var/log/messages | grep puppetd"
fi

export FACTERLIB=/var/lib/puppet/facts
