match '/node/:action/:id' => 'node'
match '/nodes' => 'node#list'
match '/reports.yml' => 'node#store_report',  :via => 'post'
match '/klass/:action/:id' => 'klass'
match '/install/:action/:id' => 'klass'
