#!/bin/bash

FILES="/var/named/master/*.zone"

echo "##################"
echo "# Puppet Managed #"
echo "##################"
echo "# Generated by $0"

for m in $FILES
do
        zone=`echo $m|sed 's/\/var\/named\/master\///g'|sed 's/\.zone//g'`
        file=`echo $m|sed 's/\/var\/named\///g'`
        echo "zone \"${zone}\" { type master; file \"${file}\"; };"
done


