#!/bin/bash

# Fa un dump de totes les bases de dades a /backup/mysqldumps
# crea un fitxer per cada base de dades

if command -v mysql &> /dev/null
then
  mkdir -p /backup/mysqldumps
  databases=`mysql -uroot -e "SHOW DATABASES;" | tr -d "| " | grep -v Database`
  for db in $databases; do
    if [[ "$db" != "information_schema" ]] && [[ "$db" != "performance_schema" ]] && [[ "$db" != "mysql" ]] && [[ "$db" != _* ]] ; then
      echo "Dumping database: $db"
      mysqldump -uroot $db > /backup/mysqldumps/$db.sql
    fi
  done
fi
